name: code041/npm_publish
description: 'composite run action'
author: Felipe Luiz Bill
branding:
  icon: "activity"
  color: "blue"


inputs:
  nome:
    description: nome da pessoa
    required: true

runs:
  using: "composite"
  steps: 
    - name: Echo
      shell: bash
      run: |
        echo ${{ inputs.nome }}