name: code041/npm_publish
description: 'NPM publishing action'
author: Felipe Luiz Bill
branding:
  icon: "activity"
  color: "blue"

inputs:
  token:
    description: GitHub token with read and write privileges over packages
    required: true
  organization:
    description: Organization repository name
    required: true
  lib_name:
    description: Library name
    required: true

runs:
  using: "composite"
  steps: 
    - name: Code checkout
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}
    - name: Git config
      shell: bash
      run: |
        git config --global user.email "${{github.actor}}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"
        echo "git configured"
        echo "installing node"
    - name: Install Node
      uses: actions/setup-node@v4.0.1
      with:
          node-version: 18
    - name: NPM config
      shell: bash
      run: |
        npm config set @${{ inputs.organization }}:registry https://npm.pkg.github.com/
        npm config set //npm.pkg.github.com/:_authToken=${{ inputs.token }}
    - name: Artifact building
      shell: bash
      run: |
        npm cache clean --force
        echo 'cache cleansed'
        npm install
        echo 'dependencies installed'
        echo ${{ inputs.lib_name }}
        npm run build ${{ inputs.lib_name }}
        echo 'building finished'
    - name: Artifact publishing
      shell: bash
      run: |
        cd dist/${{ inputs.lib_name }}
        echo 'publishing to registry'
        npm publish
