name: code041/npm_publish
description: 'composite run action'

inputs:
  nome:
    description: nome da pessoa
    required: true

runs:
  using: "composite"
  steps: 
    - name: Echo
      shell: bash
      run: |
        echo ${{ inputs.nome }}