name: code041/npm_publish
description: 'NPM publishing action'
author: Felipe Luiz Bill
branding:
  icon: "activity"
  color: "blue"

inputs:
  nome:
    description: nome da pessoa
    required: true

runs:
  using: "composite"
  steps: 
    - name: Code checkout
      uses: actions/checkout@latest
      with:
        token: ${{ secrets.NPM_REGISTRY_TOKEN }}
      run: |
        echo ${{ github.actor }}
        echo ${{ inputs.nome }}