name: code041/npm_publish
description: 'NPM publishing action'
author: Felipe Luiz Bill
branding:
  icon: "activity"
  color: "blue"

inputs:
  token:
    description: GitHub token with read and write privileges over packages
    required: true

runs:
  using: "composite"
  steps: 
    - name: Code checkout
      uses: actions/checkout@latest
      with:
        token: ${{ inputs.token }}