name: Label PR

on:
  push:
    branches:
      - "*"

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: "code041/npm_publish@latest"
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}